# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Duuetblast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memeblast
  pod "TransitionButton"
  pod 'WNPhysicsEngine'
  pod 'PopupDialog', '~> 0.9'
  target 'DuuetblastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DuuetblastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
